authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
]

dev_4/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('accounts/',
         include(('authapp.urls', 'auth'), namespace='auth')),
]

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
]

authapp/models.py
from django.db import models

# Create your models here.

mainapp/models.py
from django.db import models

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'password1',
            'password2',
            'email',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'
            item.help_text = ''

authapp/views.py
import django.contrib.auth as auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import LoginForm, RegisterForm


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            auth.login(request, form.get_user())
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = LoginForm()

    context = {
        'page_title': 'Авторизация',
        'form': form,
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        form = RegisterForm()

    context = {
        'page_title': 'Регистрация',
        'form': form,
    }
    return render(request, 'authapp/register.html', context)

mainapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render




def index(request):
    context = {
        'page_title': 'ЛДМШ',
    }
    return render(request, 'mainapp/index.html', context)

authapp/templates/authapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>{{ page_title|capfirst }}</title>
    <link rel="icon" href="static/img/favicon.ico" type="image/x-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="static/css/main.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

    <!-- Bootstrap core CSS -->
    <link href="//cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

<style>

.form-horizontal{
 background: #fff;
 padding-bottom: 40px;
 border-radius: 15px;
 text-align: center;
}


.form-horizontal .heading{
 display: block;
 font-size: 30px;
 font-weight: 700;
 padding: 25px 0;
 border-bottom: 1px solid #0b5dd6;
 margin-bottom: 30px;
}


.form-horizontal .form-control{
 background: #f0f0f0;
 border: none;
 border-radius: 20px;
 box-shadow: none;
 padding: 0 20px 0 20px;
 height: 40px;
 font-size: 12px;
}


.form-horizontal .btn{
 float: bottom;
 font-size: 14px;
 color: #fff;
 background: #4187ee;
 border-radius: 30px;
 padding: 10px 25px;
 border: none;
}


</style>

</head>
<body class="bg-primary">

{% block content %}
{% endblock %}

</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
<title>{{ page_title|capfirst }}</title>
{% block content %}

<div class="container" style="margin-top: 5%;">
 <div class="row">

 <div class="col-md-offset-3 col-md-6">
 <form method="post" class="form-horizontal bg-gradient">
    <span class="heading" style="color: black">Авторизация</span>
     <div style="width: 78%; margin-left: auto; margin-right: auto; font-size: 13px; color: black;">
        {% csrf_token %}
        {{ form.as_p }}
     </div>
        <input class="btn btn-default" style="margin-right: 33%;" type="submit"  value="Войти">
        <a class="btn btn-default"  href="{% url 'auth:register' %}">Зарегестрироваться</a>
    </div>
 </form>
 </div>
 </div>

{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
<title>{{ page_title|capfirst }}</title>
{% block content %}





<div class="container" style="margin-top: 5%;">
 <div class="row">

 <div class="col-md-offset-3 col-md-6">
 <form method="post" enctype="multipart/form-data" class="form-horizontal">
    <span class="heading" style="color: black">Регистрация</span>
     <div style="width: 78%; margin-left: auto; margin-right: auto; font-size: 13px; color: black;">
         {% csrf_token %}
         {{ form.as_p }}
     </div>
        <input class="btn btn-default" style="margin-right: 19%;" type="submit" value="Зарегистрироваться">
        <a class="btn btn-default" href="{% url 'auth:login' %}">Уже есть аккаунт?</a>
    </div>
 </form>
 </div>
 </div>


{% endblock %}

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>Лесниковская детская музыкальная школа</title>
    <link rel="icon" href="static/img/favicon.ico" type="image/x-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="static/css/main.css">


    <!-- Bootstrap core CSS -->
    <link href="//cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

<style>
#calendar2 {
  width: 100%;
  font: monospace;
  line-height: 1.2em;
  font-size: 15px;
  text-align: center;
}
#calendar2 thead tr:last-child {
  font-size: small;
  color: rgb(255, 255, 255);
}
#calendar2 thead tr:nth-child(1) td:nth-child(2) {
  color: rgb(255, 255, 255);
}
#calendar2 thead tr:nth-child(1) td:nth-child(1):hover, #calendar2 thead tr:nth-child(1) td:nth-child(3):hover {
  cursor: pointer;
}
#calendar2 tbody td {
  color: rgb(255, 255, 255);
}
#calendar2 tbody td:nth-child(n+6), #calendar2 .holiday {
  color: rgb(93, 191, 236);
}
#calendar2 tbody td.today {
  background: rgb(31, 89, 183);
  color: rgb(255, 255, 255);
}



</style>

</head>
<body class="bg-primary">


{% block content %}
{% endblock %}


</body>
<bottom>

{% block bottom %}
{% endblock %}

</bottom>
</html>